# Generated by Django 5.0.7 on 2024-07-24 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codice', models.CharField(max_length=20, unique=True)),
                ('provincia', models.CharField(max_length=2)),
                ('comune', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=200)),
                ('latitudine', models.FloatField()),
                ('longitudine', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Misurazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('pm10', models.FloatField(blank=True, null=True)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('no2', models.FloatField(blank=True, null=True)),
                ('o3', models.FloatField(blank=True, null=True)),
                ('stazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.stazione')),
            ],
        ),
    ]
