# Generated by Django 4.2.18 on 2025-02-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='stazione',
            name='entertainment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stazione',
            name='nature',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stazione',
            name='nightlife',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stazione',
            name='tourism',
            field=models.FloatField(default=0),
        ),
    ]
