# Generated by Django 5.0.7 on 2024-07-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='description',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='users.userpreferences'),
        ),
    ]
