# Generated by Django 5.0.7 on 2024-07-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userpreferences_description_userpreferences_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='description',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
