# Generated by Django 5.0.7 on 2024-07-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userpreferences_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='avoid_highways',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='avoid_tolls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='avoid_traffic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='duration_preference',
            field=models.CharField(choices=[('shortest', 'Percorso più breve'), ('fastest', 'Percorso più veloce')], default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='prefer_lit_routes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='prefer_parks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='scenic_route',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='transport_mode',
            field=models.CharField(choices=[('car', 'Automobile'), ('bike', 'Bicicletta'), ('foot', 'A piedi'), ('public_transport', 'Trasporto pubblico')], default=False, max_length=50),
        ),
    ]
