# Generated by Django 5.0.7 on 2024-07-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userpreferences_avoid_highways_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='description',
        ),
    ]
