# Generated by Django 5.0.7 on 2024-08-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_userpreferences_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='avoid_highways',
            field=models.IntegerField(choices=[(-2, 'Molto negativo'), (-1, 'Negativo'), (0, 'Neutro'), (1, 'Positivo'), (2, 'Molto positivo')], default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='avoid_tolls',
            field=models.IntegerField(choices=[(-2, 'Molto negativo'), (-1, 'Negativo'), (0, 'Neutro'), (1, 'Positivo'), (2, 'Molto positivo')], default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='avoid_traffic',
            field=models.IntegerField(choices=[(-2, 'Molto negativo'), (-1, 'Negativo'), (0, 'Neutro'), (1, 'Positivo'), (2, 'Molto positivo')], default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='prefer_lit_routes',
            field=models.IntegerField(choices=[(-2, 'Molto negativo'), (-1, 'Negativo'), (0, 'Neutro'), (1, 'Positivo'), (2, 'Molto positivo')], default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='prefer_parks',
            field=models.IntegerField(choices=[(-2, 'Molto negativo'), (-1, 'Negativo'), (0, 'Neutro'), (1, 'Positivo'), (2, 'Molto positivo')], default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='scenic_route',
            field=models.IntegerField(choices=[(-2, 'Molto negativo'), (-1, 'Negativo'), (0, 'Neutro'), (1, 'Positivo'), (2, 'Molto positivo')], default=0),
        ),
    ]
