# Generated by Django 5.0.7 on 2024-08-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_userpreferences_avoid_highways_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='duration_preference',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='fastest_path',
            field=models.IntegerField(choices=[(-2, 'Molto negativo'), (-1, 'Negativo'), (0, 'Neutro'), (1, 'Positivo'), (2, 'Molto positivo')], default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='shortest_path',
            field=models.IntegerField(choices=[(-2, 'Molto negativo'), (-1, 'Negativo'), (0, 'Neutro'), (1, 'Positivo'), (2, 'Molto positivo')], default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='transport_mode',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('foot', 'By walk')], default=False, max_length=50),
        ),
    ]
