# Generated by Django 5.0.7 on 2024-08-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_userpreferences_duration_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='avoid_highways',
            field=models.IntegerField(choices=[(-2, 'Strongly against'), (-1, 'Against'), (0, 'Neutral'), (1, 'In favor'), (2, 'Strongly in favor')], default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='avoid_tolls',
            field=models.IntegerField(choices=[(-2, 'Strongly against'), (-1, 'Against'), (0, 'Neutral'), (1, 'In favor'), (2, 'Strongly in favor')], default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='avoid_traffic',
            field=models.IntegerField(choices=[(-2, 'Strongly against'), (-1, 'Against'), (0, 'Neutral'), (1, 'In favor'), (2, 'Strongly in favor')], default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='fastest_path',
            field=models.IntegerField(choices=[(-2, 'Strongly against'), (-1, 'Against'), (0, 'Neutral'), (1, 'In favor'), (2, 'Strongly in favor')], default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='prefer_lit_routes',
            field=models.IntegerField(choices=[(-2, 'Strongly against'), (-1, 'Against'), (0, 'Neutral'), (1, 'In favor'), (2, 'Strongly in favor')], default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='prefer_parks',
            field=models.IntegerField(choices=[(-2, 'Strongly against'), (-1, 'Against'), (0, 'Neutral'), (1, 'In favor'), (2, 'Strongly in favor')], default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='scenic_route',
            field=models.IntegerField(choices=[(-2, 'Strongly against'), (-1, 'Against'), (0, 'Neutral'), (1, 'In favor'), (2, 'Strongly in favor')], default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='shortest_path',
            field=models.IntegerField(choices=[(-2, 'Strongly against'), (-1, 'Against'), (0, 'Neutral'), (1, 'In favor'), (2, 'Strongly in favor')], default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='transport_mode',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('foot', 'Walk')], default=False, max_length=50),
        ),
    ]
