# Generated by Django 5.0.7 on 2024-08-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_userpreferences_avoid_highways_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='interest_points',
            field=models.FloatField(choices=[(-1, 'Strongly against'), (-0.5, 'Against'), (0, 'Neutral'), (0.5, 'In favor'), (1, 'Strongly in favor')], default=0),
        ),
    ]
