# Generated by Django 5.0.7 on 2024-09-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_userpreferences_interest_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='avoid_highways',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='avoid_tolls',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='avoid_traffic',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='fastest_path',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='interest_points',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='prefer_lit_routes',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='prefer_parks',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='scenic_route',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='shortest_path',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='transport_mode',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='entertainment',
            field=models.FloatField(choices=[(-1, 'Strongly against'), (-0.5, 'Against'), (0, 'Neutral'), (0.5, 'In favor'), (1, 'Strongly in favor')], default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='nature',
            field=models.FloatField(choices=[(-1, 'Strongly against'), (-0.5, 'Against'), (0, 'Neutral'), (0.5, 'In favor'), (1, 'Strongly in favor')], default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='nightlife',
            field=models.FloatField(choices=[(-1, 'Strongly against'), (-0.5, 'Against'), (0, 'Neutral'), (0.5, 'In favor'), (1, 'Strongly in favor')], default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='tourism',
            field=models.FloatField(choices=[(-1, 'Strongly against'), (-0.5, 'Against'), (0, 'Neutral'), (0.5, 'In favor'), (1, 'Strongly in favor')], default=0),
        ),
    ]
