# Generated by Django 5.0.7 on 2024-09-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_userpreferences_avoid_highways_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='avoid_highways',
            field=models.FloatField(choices=[(-1, 'Strongly against'), (-0.5, 'Against'), (0, 'Neutral'), (0.5, 'In favor'), (1, 'Strongly in favor')], default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='avoid_tolls',
            field=models.FloatField(choices=[(-1, 'Strongly against'), (-0.5, 'Against'), (0, 'Neutral'), (0.5, 'In favor'), (1, 'Strongly in favor')], default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='avoid_traffic',
            field=models.FloatField(choices=[(-1, 'Strongly against'), (-0.5, 'Against'), (0, 'Neutral'), (0.5, 'In favor'), (1, 'Strongly in favor')], default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='prefer_lit_routes',
            field=models.FloatField(choices=[(-1, 'Strongly against'), (-0.5, 'Against'), (0, 'Neutral'), (0.5, 'In favor'), (1, 'Strongly in favor')], default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='prefer_parks',
            field=models.FloatField(choices=[(-1, 'Strongly against'), (-0.5, 'Against'), (0, 'Neutral'), (0.5, 'In favor'), (1, 'Strongly in favor')], default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='scenic_route',
            field=models.FloatField(choices=[(-1, 'Strongly against'), (-0.5, 'Against'), (0, 'Neutral'), (0.5, 'In favor'), (1, 'Strongly in favor')], default=0),
        ),
    ]
