# Generated by Django 5.2.15 on 2026-06-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_userpreferences_avoid_highways_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_pathology',
            field=models.CharField(choices=[('none', 'No specific condition'), ('respiratory', 'Respiratory condition'), ('cardiac', 'Cardiac condition'), ('arthritis', 'Arthritis or joint pain'), ('mental', 'Mental health'), ('mobility', 'Limited mobility'), ('diabetes', 'Diabetes')], default='none', help_text='Default clinical condition pre-selected when planning a route.', max_length=20),
        ),
    ]
