import os, shutil
from django.contrib.auth.models import User
from django.db import connection
from users.models import UserPreferences


# Function to reset table id conuter
def reset_id_counter(table_name):
    with connection.cursor() as cursor:
        cursor.execute(f"DELETE FROM sqlite_sequence WHERE name='{table_name}';")


# Function to delete folders generated by uploading profile images or other media
def delete_folders():
    folders = ["static/uploaded_profile_pictures"]
    for folder in folders:
        try:
            if os.path.exists(folder):
                shutil.rmtree(folder)
        except FileNotFoundError:
            pass


# Function to reset the database
def erase_db():
    User.objects.all().delete()
    UserPreferences.objects.all().delete()
    delete_folders()


# Function to initialise the database
def init_db():
    reset_id_counter('auth_user')
    reset_id_counter('users_userprofile')
    reset_id_counter('users_userpreferences')
    reset_id_counter('users_userprofile_preferences')
    